# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': ' Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
