# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160926_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupform',
            name='updated',
        ),
    ]
