# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
