# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
            preserve_default=False,
        ),
    ]
