# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
    ]
